basePath: /
definitions:
  dtos.EventRequest:
    properties:
      eventId:
        description: ID of the event to be booked
        type: string
      locationType:
        description: The location information as to will the event will be in-person
          or virtual
        type: string
      providerId:
        description: ID of the provider for the event
        type: string
      userInfo:
        allOf:
        - $ref: '#/definitions/dtos.UserInfo'
        description: Information about the user making the booking
    type: object
  dtos.Location:
    properties:
      facility:
        description: Name of the facility
        type: string
      state:
        description: State where the provider is located
        type: string
    type: object
  dtos.ProviderRequest:
    properties:
      age:
        description: Age input for filtering providers
        type: string
      clinicalFocus:
        description: List of clinical focus areas
        items:
          type: string
        type: array
      deliveryMethod:
        description: Preferred delivery method
        type: string
      ethnicity:
        description: Ethnicity preference for filtering
        type: string
      gender:
        description: Gender preference for filtering
        type: string
      language:
        description: Language preference for filtering
        type: string
      location:
        allOf:
        - $ref: '#/definitions/dtos.Location'
        description: Location details for filtering
      therapeuticModality:
        description: Preferred therapeutic modality
        type: string
    type: object
  dtos.SearchEventRequest:
    properties:
      providerId:
        description: List of provider IDs to search for available slots
        items:
          type: string
        type: array
    type: object
  dtos.UserInfo:
    properties:
      userName:
        description: User's name
        type: string
    type: object
  healthCheck.HealthResponse:
    properties:
      message:
        type: string
      runtime:
        type: string
      status:
        type: integer
    type: object
host: func-smh-ss-webapi-stage-003.azurewebsites.net
info:
  contact: {}
  description: This API is used to manage the SOL Smart Scheduling system
  title: SOL Smart Scheduling API
  version: "1.0"
paths:
  /api/event:
    get:
      consumes:
      - application/json
      description: This function retrieves provider events based on providerId and
        eventId from the request.
      parameters:
      - description: Event ID
        in: query
        name: eventId
        type: string
      - description: Provider ID
        in: query
        name: providerId
        type: string
      produces:
      - application/json
      responses: {}
      summary: '[1] Fetch provider events'
      tags:
      - Search Providers with Events
  /api/event/book:
    post:
      consumes:
      - application/json
      description: BookingEvent handles the HTTP request for booking an event for
        a healthcare provider based on the provided event details.
      parameters:
      - description: Event booking request details
        in: body
        name: bookEventBody
        required: true
        schema:
          $ref: '#/definitions/dtos.EventRequest'
      produces:
      - application/json
      responses: {}
      summary: '[6] Book an Event'
      tags:
      - Book Event
  /api/event/list:
    post:
      consumes:
      - application/json
      description: EventSearch handles the HTTP request for searching available time
        slots of healthcare providers based on specified filters.
      parameters:
      - description: Search filters for available time slots
        in: body
        name: searchFilters
        required: true
        schema:
          $ref: '#/definitions/dtos.SearchEventRequest'
      produces:
      - application/json
      responses: {}
      summary: '[3] Search Available Time Slots'
      tags:
      - events
  /api/healthCheck:
    get:
      consumes:
      - application/json
      description: HealthCheckHandler checks the health of the service and returns
        the status in JSON format.
      produces:
      - application/json
      responses:
        "200":
          description: Health check successful
          schema:
            $ref: '#/definitions/healthCheck.HealthResponse'
      security:
      - BearerAuth: []
      summary: '[0] Health Check'
      tags:
      - Health Check
  /api/provider:
    post:
      consumes:
      - application/json
      description: ProviderSearch handles the HTTP request for searching healthcare
        providers based on various filters and returns the results.
      parameters:
      - description: Search filters for healthcare providers
        in: body
        name: f
        required: true
        schema:
          $ref: '#/definitions/dtos.ProviderRequest'
      produces:
      - application/json
      responses: {}
      summary: '[2] Search for Healthcare Providers'
      tags:
      - providers
schemes:
- https
securityDefinitions:
  BearerAuth:
    description: This API requires a Bearer token in the `Authorization` header.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
